### ISSUE TITLE
CookieJar genserver expire option

### ISSUE THREAD

**Issue by avierr** [princemaple/cookie_jar#11]
when I create a new server using: {:ok, jar} = CookieJar.new
and there is a crash in **my** process , I loose the reference to jar process and I don't have a way to kill the jar.

I use cookiejar to make thousands of requests an hour and end up with a lot of lingering CookieJar processes which cannot be cleaned up.

It would be nice if I could initialize CookieJar.new([expiresIn: 3600]) so that it would close on it's own if I loose the reference to it.

**Comment by avierr** [comment]
ah got you!
I did not know GenServer.start_link works this way. I ll just have to move the initialization to the right place.
Thanks for the quick reply.

**Comment by princemaple** [comment]
No worries mate, glad you found this little project useful. Have fun!
