### ISSUE TITLE
Expire cookies

### ISSUE THREAD

**Issue by CrowdHailer** [princemaple/cookie_jar#20]
I use cookie jar test my applications. I have just discovered that it doesn't handle expiring cookies. I have a test as follows

- check I CANT view admin page
- login
- check I CAN view admin page
- logout
- check I CANT view admin page <- At this step no cookie should get sent. 

My response to the logout step included `set-cookie: my_app_session=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; max-age=0; HttpOnly`

Would it be possible to add a simple feature that if it found max-age=0 automatically expired the cookie?

**Comment by princemaple** [comment]
Ah forgot to reply, sorry.

The scope of this lib is hacking / scraping things. it doesn't really concern about validness of cookie. I think there are better ways of testing web apps. You can test it in unit tests with prepared `conn`s. Or in your case, there should be something in `Raxx`/`Ace` that's the equivalent, right? Going E2E on cookie sounds like testing browser functionality to me.

Regards,
Po
