### ISSUE TITLE
selective sending cookies

### ISSUE THREAD

**Issue by derek-zhou** [princemaple/cookie_jar#40]
It looks like the `HTTPoision` wrapper send all the cookies in the jar, regardless what domain the request is going to?
It would be nice if `cookie_jar` can detect domain name and filter down the cookies, just like what a browser do.

**Comment by derek-zhou** [comment]
Let me try to make a PR. It will take a few days.

**Comment by princemaple** [comment]
Take your time!

**Comment by princemaple** [comment]
Thanks again for the PR!
